services:
  mysql:
    image: mysql:8.0
    container_name: stock_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-stock_db}
      MYSQL_USER: ${MYSQL_USER:-stockuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-stockpass123}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    platform: linux/amd64
    networks:
      - stock_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  streamlit:
    build: .
    container_name: stock_streamlit
    ports:
      - "${PORT:-8501}:8501"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER:-stockuser}
      DB_PASSWORD: ${MYSQL_PASSWORD:-stockpass123}
      DB_NAME: ${MYSQL_DATABASE:-stock_db}
      PORT: ${PORT:-8501}
    volumes:
      - ./app:/app
    networks:
      - stock_network
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=${PORT:-8501}

networks:
  stock_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local